### PR TITLE
#161254611 setup test environment

### PR DESCRIPTION
**Pull request by TheSteelGuy**
#### What does this PR do?
- setup test environment for the application

#### Description of Task to be completed?
- Create setupTest.js, download jest and enzyme for testing

#### How should this be manually tested?
- Clone this repository 
```git clone https://github.com/andela/ah-orcas-frontend.git```
- Change the working directory to the project folder
``` cd ah-orcas-frontend```
- Checkout to the appropriate branch
``` git checkout ch-setup-test-environment-161254611```
- Install the required dependencies:
```npm install```
- Run the test
```npm test```
- test will pass

#### Any background context you want to provide?
- The task involved just adding the relevant dependencies(enzyme, jest. No test are written yet)

#### What are the relevant pivotal tracker stories?
[#161254611](https://www.pivotaltracker.com/story/show/161254611)

#### Checklist:
- [X] My code follows the style guidelines of this project
- [X] At least 2 people have reviewed my PR
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] My PR has one commit.

### CODE REVIEW

**Review by evamaina — CHANGES_REQUESTED** [review]
Solve the hound issue and you will be good to go

**Review by abadojack — APPROVED** [review]
LGTM

**Review by wrotich — APPROVED** [review]
LGTM

**Review by evamaina — APPROVED** [review]

**Review by Eyansky — APPROVED** [review]
LGTM

**Pull request merged**
