### PR TITLE
#161254622 create articles

### PR DESCRIPTION
**Pull request by Gidraf**
#### What does this PR do?
Allow user to view and create articles
#### Description of Task to be completed?
```Create article```
```View articles```
```view single article```
```delete article```
```update article```
#### How should this be manually tested?
- Clone this repository
`git clone https://github.com/andela/ah-orcas-frontend.git`
- Change the working directory to the project folder
`cd ah-orcas-frontend`
- Checkout to the appropriate branch
`git checkout ft-create-articles-161254622`
- Install the required dependencies:
     `npm start`
should be able to see the first ten articles in home
if authenticated you should be able to create
 
#### What are the relevant pivotal tracker stories?
 [#161254616](https://www.pivotaltracker.com/story/show/161254616)
#### Screenshots (if appropriate)
image
image
image
image

#### Checklist:

- [X] My code follows the style guidelines of this project
- [ ] At least 2 people have reviewed my PR
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] My PR has one commit.

### CODE REVIEW

**Comment by Eyansky** [comment]
Travis did not build. Why?

**Comment by evamaina** [comment]
Squash your commits into one. Its very hard to rebase from your work

**Comment by Eyansky** [comment]
If it is complete change the label from WIP to finished.

**Review by code-sleuth — APPROVED** [review]
LGTM

**Pull request merged**
