### PR TITLE
#162236117 pull request template

### PR DESCRIPTION
**Pull request by Eyansky**
#### What does this PR do?
- Creates a pull request template.

#### Description of Task to be completed?
- As we create pull requests we should have consistent descriptions of tasks undertaken so that they can be be easily reviewed and understood by the whole team.

#### How should this be manually tested?
- Clone this repo
```
$ git clone https://github.com/andela/ah-orcas-frontend
```
- Navigate to this branch
```
$ git checkout ch-pr-template-162236117
```
- Read the template format in .github file called pull_request_template.md

#### Any background context you want to provide?
- This is just the template of how all pull requests should look like.

#### What are the relevant pivotal tracker stories?
- [#162236117](https://www.pivotaltracker.com/story/show/162236117)

#### Screenshots (if appropriate)
screenshot 2018-11-27 at 15 25 43

#### What does this PR do?
```sample answer ```
#### Description of Task to be completed?
```sample answer ```
#### How should this be manually tested?
```sample answer ```
#### Any background context you want to provide?
```sample answer ```
#### What are the relevant pivotal tracker stories?
```sample answer ```
#### Screenshots (if appropriate)
- Add screen short if available
#### Questions:
```Sample Question ```

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My PR has one commit.

### CODE REVIEW

**Review by wrotich — COMMENTED** [review]
Why do you want to merge the changes to master?, There are three commits in this PR, Kindly check on the how you created your branch, which branch did you branch from?

**Review by wrotich — CHANGES_REQUESTED** [review]
Check on the three commits in your PR, something does not add up

**Comment by Eyansky** [comment]
@wrotich  I have rectified that error. Thank you for pointing that out.

**Comment by wrotich** [comment]
@Eyansky Your commit message is also wrong, check for the correct format

**Review by evamaina — CHANGES_REQUESTED** [review]
Why do you have three commits in one pr? You should squash them into one. seems like you have created a new branch from your previous branch for setting up react instead of from develop branch. Always make sure to checkout develop while creating a new branch in order to avoid merge conflicts.Hope you have followed the right procedure.

**Comment by Eyansky** [comment]
@evamaina I have only one. Kindly check clearly.

**Comment by evamaina** [comment]
> @evamaina I have only one. Kindly check clearly.

Seems you have changed. had seen your previous commit for setting up react in this new pr. Wonder how it got there

**Comment by kipropbrian** [comment]
For the screenshot, can you show how it looks once the markdown is rendered.

**Review by evamaina — APPROVED** [review]

**Review by wrotich — APPROVED** [review]

**Comment by kipropbrian** [comment]
We have also been doing an experimental experiment with the github template where we add a  checklist to the end. Could you add that, the checklist is here https://gist.github.com/kipropbrian/23942c18e65f4cf14b6746d3bc0ba6b3

**Comment by Eyansky** [comment]
@kipropbrian why add a screenshot when I can just add it after the screenshot 😁. Kindly check it again

**Comment by kipropbrian** [comment]
Nice @Eyansky 
You should add the checklist at the end of the PR template

**Review by kipropbrian — APPROVED** [review]

**Comment by Eyansky** [comment]
@kipropbrian changes requested have been made.

**Comment by kipropbrian** [comment]
Can you make the checklist font be the same as the rest of the headings, it should be the same as the other headings. e.g questions

**Comment by Eyansky** [comment]
@kipropbrian changes requested have been done.

**Pull request merged**
