### PR TITLE
#161254626 Add/view tags

### PR DESCRIPTION
**Pull request by Gidraf**
#### What does this PR do?
Allow user to view and create articles
#### Description of Task to be completed?
```Add tags to article```
``` view tags```
#### How should this be manually tested?
- Clone this repository
`git clone https://github.com/andela/ah-orcas-frontend.git`
- Change the working directory to the project folder
`cd ah-orcas-frontend`
- Checkout to the appropriate branch
`git checkout ft-view-tags-161254626`
- Install the required dependencies:
     `npm start`
should be able to add tags upon article creation
 
#### What are the relevant pivotal tracker stories?
[#161254626](https://www.pivotaltracker.com/story/show/161254626)

image
image

#### Checklist:

- [X] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] My PR has one commit.

### CODE REVIEW

**Review by wrotich — CHANGES_REQUESTED** [review]
Your commit message is wrong

**Review by TheSteelGuy — APPROVED** [review]

**Review by TheSteelGuy — CHANGES_REQUESTED** [review]
rebase your work

**Review by wrotich — APPROVED** [review]

**Review by TheSteelGuy — APPROVED** [review]
LGTM

**Review by evamaina — APPROVED** [review]
LGTM

**Pull request merged**
