### PR TITLE
#161254609 setup react

### PR DESCRIPTION
**Pull request by Eyansky**
#### What does this PR do?
- Setup a new react app.
- setup eslint using airbnb configurations.

#### Description of Task to be completed?
- Use the create-react-app tool to setup the react boilerplate using the Airbnb linting option. 

#### How should this be manually tested?
- Clone this repo
```
$ git clone https://github.com/andela/ah-orcas-frontend
```
- Navigate to this branch
```
$ git checkout ch-react-setup-161254609
```
- install react packages. 
```
$ npm install
```
- run the app.
```
- npm start
```
#### Any background context you want to provide?
- This is just the setup for a blank react js project.

#### What are the relevant pivotal tracker stories?
- [#161254609](https://www.pivotaltracker.com/story/show/161254609)

#### Screenshots (if appropriate)
screenshot 2018-11-27 at 14 04 17

### CODE REVIEW

**Review by evamaina — CHANGES_REQUESTED** [review]
Remove the logo and everything else that we do not need. For example, in the app.js you can remove all the content that is in the div. Also in app.css remove all the CSS that is meant for the header and logo

**Comment by Eyansky** [comment]
@evamaina it is done. Kindly review it again. See screenshot above.

**Review by evamaina — APPROVED** [review]

**Review by wrotich — DISMISSED** [review]
Check the comment below @Eyansky

**Review by wrotich — COMMENTED** [review]
@Eyansky Why are we doing git init?

**Review by Gidraf — APPROVED** [review]
LGTM

**Review by TheSteelGuy — APPROVED** [review]
LGTM

**Comment by Eyansky** [comment]
@wrotich I have removed that. Thank you.

**Pull request merged**
